<?php
/**
 * EmpresaInputTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia.  **Optimizaciones de Rendimiento:** * **Rate Limiting:** Todas las rutas están limitadas a 60 peticiones por minuto por IP para prevenir abusos. En caso de exceder el límite, la API retornará un código `429 Too Many Requests`. * **Caché:** El endpoint de estadísticas (`/admin/estadisticas`) utiliza caché en memoria con un TTL (Time To Live) de 5 minutos (300 segundos) para reducir la carga sobre la base de datos y mejorar los tiempos de respuesta.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * EmpresaInputTest Class Doc Comment
 *
 * @category    Class
 * @description EmpresaInput
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmpresaInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EmpresaInput"
     */
    public function testEmpresaInput()
    {
    }

    /**
     * Test attribute "nombre_empresa"
     */
    public function testPropertyNombreEmpresa()
    {
    }

    /**
     * Test attribute "rut_empresa"
     */
    public function testPropertyRutEmpresa()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "tipo_empresa"
     */
    public function testPropertyTipoEmpresa()
    {
    }

    /**
     * Test attribute "contacto_nombre"
     */
    public function testPropertyContactoNombre()
    {
    }

    /**
     * Test attribute "contacto_email"
     */
    public function testPropertyContactoEmail()
    {
    }

    /**
     * Test attribute "beneficios"
     */
    public function testPropertyBeneficios()
    {
    }
}
