<?php
/**
 * EmpresaInput
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia.  **Optimizaciones de Rendimiento:** * **Rate Limiting:** Todas las rutas están limitadas a 60 peticiones por minuto por IP para prevenir abusos. En caso de exceder el límite, la API retornará un código `429 Too Many Requests`. * **Caché:** El endpoint de estadísticas (`/admin/estadisticas`) utiliza caché en memoria con un TTL (Time To Live) de 5 minutos (300 segundos) para reducir la carga sobre la base de datos y mejorar los tiempos de respuesta.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmpresaInput Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmpresaInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmpresaInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'nombre_empresa' => 'string',
        'rut_empresa' => 'string',
        'email' => 'string',
        'tipo_empresa' => 'string',
        'contacto_nombre' => 'string',
        'contacto_email' => 'string',
        'beneficios' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'nombre_empresa' => null,
        'rut_empresa' => null,
        'email' => 'email',
        'tipo_empresa' => null,
        'contacto_nombre' => null,
        'contacto_email' => 'email',
        'beneficios' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nombre_empresa' => 'nombre_empresa',
        'rut_empresa' => 'rut_empresa',
        'email' => 'email',
        'tipo_empresa' => 'tipo_empresa',
        'contacto_nombre' => 'contacto_nombre',
        'contacto_email' => 'contacto_email',
        'beneficios' => 'beneficios'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nombre_empresa' => 'setNombreEmpresa',
        'rut_empresa' => 'setRutEmpresa',
        'email' => 'setEmail',
        'tipo_empresa' => 'setTipoEmpresa',
        'contacto_nombre' => 'setContactoNombre',
        'contacto_email' => 'setContactoEmail',
        'beneficios' => 'setBeneficios'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nombre_empresa' => 'getNombreEmpresa',
        'rut_empresa' => 'getRutEmpresa',
        'email' => 'getEmail',
        'tipo_empresa' => 'getTipoEmpresa',
        'contacto_nombre' => 'getContactoNombre',
        'contacto_email' => 'getContactoEmail',
        'beneficios' => 'getBeneficios'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TIPO_EMPRESA_CONTRATACION_DIRECTA = 'contratacion-directa';
    const TIPO_EMPRESA_EST = 'est';
    const TIPO_EMPRESA_OUTSOURCING = 'outsourcing';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoEmpresaAllowableValues()
    {
        return [
            self::TIPO_EMPRESA_CONTRATACION_DIRECTA,
            self::TIPO_EMPRESA_EST,
            self::TIPO_EMPRESA_OUTSOURCING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['nombre_empresa'] = isset($data['nombre_empresa']) ? $data['nombre_empresa'] : null;
        $this->container['rut_empresa'] = isset($data['rut_empresa']) ? $data['rut_empresa'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['tipo_empresa'] = isset($data['tipo_empresa']) ? $data['tipo_empresa'] : null;
        $this->container['contacto_nombre'] = isset($data['contacto_nombre']) ? $data['contacto_nombre'] : null;
        $this->container['contacto_email'] = isset($data['contacto_email']) ? $data['contacto_email'] : null;
        $this->container['beneficios'] = isset($data['beneficios']) ? $data['beneficios'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['nombre_empresa'] === null) {
            $invalidProperties[] = "'nombre_empresa' can't be null";
        }
        if ($this->container['rut_empresa'] === null) {
            $invalidProperties[] = "'rut_empresa' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['tipo_empresa'] === null) {
            $invalidProperties[] = "'tipo_empresa' can't be null";
        }
        $allowedValues = $this->getTipoEmpresaAllowableValues();
        if (!is_null($this->container['tipo_empresa']) && !in_array($this->container['tipo_empresa'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'tipo_empresa', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['contacto_nombre'] === null) {
            $invalidProperties[] = "'contacto_nombre' can't be null";
        }
        if ($this->container['contacto_email'] === null) {
            $invalidProperties[] = "'contacto_email' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nombre_empresa
     *
     * @return string
     */
    public function getNombreEmpresa()
    {
        return $this->container['nombre_empresa'];
    }

    /**
     * Sets nombre_empresa
     *
     * @param string $nombre_empresa nombre_empresa
     *
     * @return $this
     */
    public function setNombreEmpresa($nombre_empresa)
    {
        $this->container['nombre_empresa'] = $nombre_empresa;

        return $this;
    }

    /**
     * Gets rut_empresa
     *
     * @return string
     */
    public function getRutEmpresa()
    {
        return $this->container['rut_empresa'];
    }

    /**
     * Sets rut_empresa
     *
     * @param string $rut_empresa rut_empresa
     *
     * @return $this
     */
    public function setRutEmpresa($rut_empresa)
    {
        $this->container['rut_empresa'] = $rut_empresa;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets tipo_empresa
     *
     * @return string
     */
    public function getTipoEmpresa()
    {
        return $this->container['tipo_empresa'];
    }

    /**
     * Sets tipo_empresa
     *
     * @param string $tipo_empresa tipo_empresa
     *
     * @return $this
     */
    public function setTipoEmpresa($tipo_empresa)
    {
        $allowedValues = $this->getTipoEmpresaAllowableValues();
        if (!in_array($tipo_empresa, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'tipo_empresa', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_empresa'] = $tipo_empresa;

        return $this;
    }

    /**
     * Gets contacto_nombre
     *
     * @return string
     */
    public function getContactoNombre()
    {
        return $this->container['contacto_nombre'];
    }

    /**
     * Sets contacto_nombre
     *
     * @param string $contacto_nombre contacto_nombre
     *
     * @return $this
     */
    public function setContactoNombre($contacto_nombre)
    {
        $this->container['contacto_nombre'] = $contacto_nombre;

        return $this;
    }

    /**
     * Gets contacto_email
     *
     * @return string
     */
    public function getContactoEmail()
    {
        return $this->container['contacto_email'];
    }

    /**
     * Sets contacto_email
     *
     * @param string $contacto_email contacto_email
     *
     * @return $this
     */
    public function setContactoEmail($contacto_email)
    {
        $this->container['contacto_email'] = $contacto_email;

        return $this;
    }

    /**
     * Gets beneficios
     *
     * @return string[]
     */
    public function getBeneficios()
    {
        return $this->container['beneficios'];
    }

    /**
     * Sets beneficios
     *
     * @param string[] $beneficios beneficios
     *
     * @return $this
     */
    public function setBeneficios($beneficios)
    {
        $this->container['beneficios'] = $beneficios;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
