<?php
/**
 * IdEstadoBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia.  **Optimizaciones de Rendimiento:** * **Rate Limiting:** Todas las rutas están limitadas a 60 peticiones por minuto por IP para prevenir abusos. En caso de exceder el límite, la API retornará un código `429 Too Many Requests`. * **Caché:** El endpoint de estadísticas (`/admin/estadisticas`) utiliza caché en memoria con un TTL (Time To Live) de 5 minutos (300 segundos) para reducir la carga sobre la base de datos y mejorar los tiempos de respuesta.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * IdEstadoBody Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IdEstadoBody implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'id_estado_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'estado' => 'string',
        'notas_admin' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'estado' => null,
        'notas_admin' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'estado' => 'estado',
        'notas_admin' => 'notas_admin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'estado' => 'setEstado',
        'notas_admin' => 'setNotasAdmin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'estado' => 'getEstado',
        'notas_admin' => 'getNotasAdmin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ESTADO_PENDIENTE = 'pendiente';
    const ESTADO_CONTACTADO = 'contactado';
    const ESTADO_ENTREVISTA = 'entrevista';
    const ESTADO_SELECCIONADO = 'seleccionado';
    const ESTADO_NO_SELECCIONADO = 'no-seleccionado';
    const ESTADO_PROCESO_CERRADO = 'proceso-cerrado';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEstadoAllowableValues()
    {
        return [
            self::ESTADO_PENDIENTE,
            self::ESTADO_CONTACTADO,
            self::ESTADO_ENTREVISTA,
            self::ESTADO_SELECCIONADO,
            self::ESTADO_NO_SELECCIONADO,
            self::ESTADO_PROCESO_CERRADO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['estado'] = isset($data['estado']) ? $data['estado'] : null;
        $this->container['notas_admin'] = isset($data['notas_admin']) ? $data['notas_admin'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['estado'] === null) {
            $invalidProperties[] = "'estado' can't be null";
        }
        $allowedValues = $this->getEstadoAllowableValues();
        if (!is_null($this->container['estado']) && !in_array($this->container['estado'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'estado', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets estado
     *
     * @return string
     */
    public function getEstado()
    {
        return $this->container['estado'];
    }

    /**
     * Sets estado
     *
     * @param string $estado estado
     *
     * @return $this
     */
    public function setEstado($estado)
    {
        $allowedValues = $this->getEstadoAllowableValues();
        if (!in_array($estado, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'estado', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['estado'] = $estado;

        return $this;
    }

    /**
     * Gets notas_admin
     *
     * @return string
     */
    public function getNotasAdmin()
    {
        return $this->container['notas_admin'];
    }

    /**
     * Sets notas_admin
     *
     * @param string $notas_admin notas_admin
     *
     * @return $this
     */
    public function setNotasAdmin($notas_admin)
    {
        $this->container['notas_admin'] = $notas_admin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
