<?php
/**
 * PersonaInput
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProviEmplea API
 *
 * API REST para la plataforma de empleo ProviEmplea de Providencia.  **Optimizaciones de Rendimiento:** * **Rate Limiting:** Todas las rutas están limitadas a 60 peticiones por minuto por IP para prevenir abusos. En caso de exceder el límite, la API retornará un código `429 Too Many Requests`. * **Caché:** El endpoint de estadísticas (`/admin/estadisticas`) utiliza caché en memoria con un TTL (Time To Live) de 5 minutos (300 segundos) para reducir la carga sobre la base de datos y mejorar los tiempos de respuesta.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PersonaInput Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PersonaInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PersonaInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'email' => 'string',
        'nivel_educacional' => 'string',
        'titulo_carrera' => 'string',
        'anios_experiencia' => 'int',
        'competencias' => 'string[]',
        'tipo_jornada' => 'string',
        'modalidad' => 'string',
        'rango_renta' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'email' => 'email',
        'nivel_educacional' => null,
        'titulo_carrera' => null,
        'anios_experiencia' => null,
        'competencias' => null,
        'tipo_jornada' => null,
        'modalidad' => null,
        'rango_renta' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'email',
        'nivel_educacional' => 'nivel_educacional',
        'titulo_carrera' => 'titulo_carrera',
        'anios_experiencia' => 'anios_experiencia',
        'competencias' => 'competencias',
        'tipo_jornada' => 'tipo_jornada',
        'modalidad' => 'modalidad',
        'rango_renta' => 'rango_renta'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'nivel_educacional' => 'setNivelEducacional',
        'titulo_carrera' => 'setTituloCarrera',
        'anios_experiencia' => 'setAniosExperiencia',
        'competencias' => 'setCompetencias',
        'tipo_jornada' => 'setTipoJornada',
        'modalidad' => 'setModalidad',
        'rango_renta' => 'setRangoRenta'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'nivel_educacional' => 'getNivelEducacional',
        'titulo_carrera' => 'getTituloCarrera',
        'anios_experiencia' => 'getAniosExperiencia',
        'competencias' => 'getCompetencias',
        'tipo_jornada' => 'getTipoJornada',
        'modalidad' => 'getModalidad',
        'rango_renta' => 'getRangoRenta'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['nivel_educacional'] = isset($data['nivel_educacional']) ? $data['nivel_educacional'] : null;
        $this->container['titulo_carrera'] = isset($data['titulo_carrera']) ? $data['titulo_carrera'] : null;
        $this->container['anios_experiencia'] = isset($data['anios_experiencia']) ? $data['anios_experiencia'] : null;
        $this->container['competencias'] = isset($data['competencias']) ? $data['competencias'] : null;
        $this->container['tipo_jornada'] = isset($data['tipo_jornada']) ? $data['tipo_jornada'] : null;
        $this->container['modalidad'] = isset($data['modalidad']) ? $data['modalidad'] : null;
        $this->container['rango_renta'] = isset($data['rango_renta']) ? $data['rango_renta'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets nivel_educacional
     *
     * @return string
     */
    public function getNivelEducacional()
    {
        return $this->container['nivel_educacional'];
    }

    /**
     * Sets nivel_educacional
     *
     * @param string $nivel_educacional nivel_educacional
     *
     * @return $this
     */
    public function setNivelEducacional($nivel_educacional)
    {
        $this->container['nivel_educacional'] = $nivel_educacional;

        return $this;
    }

    /**
     * Gets titulo_carrera
     *
     * @return string
     */
    public function getTituloCarrera()
    {
        return $this->container['titulo_carrera'];
    }

    /**
     * Sets titulo_carrera
     *
     * @param string $titulo_carrera titulo_carrera
     *
     * @return $this
     */
    public function setTituloCarrera($titulo_carrera)
    {
        $this->container['titulo_carrera'] = $titulo_carrera;

        return $this;
    }

    /**
     * Gets anios_experiencia
     *
     * @return int
     */
    public function getAniosExperiencia()
    {
        return $this->container['anios_experiencia'];
    }

    /**
     * Sets anios_experiencia
     *
     * @param int $anios_experiencia anios_experiencia
     *
     * @return $this
     */
    public function setAniosExperiencia($anios_experiencia)
    {
        $this->container['anios_experiencia'] = $anios_experiencia;

        return $this;
    }

    /**
     * Gets competencias
     *
     * @return string[]
     */
    public function getCompetencias()
    {
        return $this->container['competencias'];
    }

    /**
     * Sets competencias
     *
     * @param string[] $competencias competencias
     *
     * @return $this
     */
    public function setCompetencias($competencias)
    {
        $this->container['competencias'] = $competencias;

        return $this;
    }

    /**
     * Gets tipo_jornada
     *
     * @return string
     */
    public function getTipoJornada()
    {
        return $this->container['tipo_jornada'];
    }

    /**
     * Sets tipo_jornada
     *
     * @param string $tipo_jornada tipo_jornada
     *
     * @return $this
     */
    public function setTipoJornada($tipo_jornada)
    {
        $this->container['tipo_jornada'] = $tipo_jornada;

        return $this;
    }

    /**
     * Gets modalidad
     *
     * @return string
     */
    public function getModalidad()
    {
        return $this->container['modalidad'];
    }

    /**
     * Sets modalidad
     *
     * @param string $modalidad modalidad
     *
     * @return $this
     */
    public function setModalidad($modalidad)
    {
        $this->container['modalidad'] = $modalidad;

        return $this;
    }

    /**
     * Gets rango_renta
     *
     * @return string
     */
    public function getRangoRenta()
    {
        return $this->container['rango_renta'];
    }

    /**
     * Sets rango_renta
     *
     * @param string $rango_renta rango_renta
     *
     * @return $this
     */
    public function setRangoRenta($rango_renta)
    {
        $this->container['rango_renta'] = $rango_renta;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
